# Enable logging for MCUboot
CONFIG_LOG=y

# Turn on a LED so we can see when Serial Recovery mode is active
CONFIG_MCUBOOT_INDICATION_LED=y


# Step 1.2 - Enable SPI driver for external flash (MCUboot)
# Step 1.2 - Enable SPI driver for MCUboot
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y
# tamaño de mi sector flash es de 4kb
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# QSPI drivers are enabled by defualt for some chips.
# Disable it explicitly to be sure QSPI is disabled.
CONFIG_NORDIC_QSPI_NOR=n 

# required by SPI driver
CONFIG_MULTITHREADING=y

# Step 4.1 - Increase number of sectors for S25FL128L
# 512 sectores = 2MB max por aplicación (suficiente para nRF52833)
# Para aplicaciones típicas nRF52833
CONFIG_BOOT_MAX_IMG_SECTORS=512

# Development settings - Disable protection for easy programming in MCUboot
# WARNING: Remove these lines for production builds
#CONFIG_NRF_APPROTECT_LOCK=n
#CONFIG_NRF_APPROTECT_USER_HANDLING=n

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4